### ISSUE TITLE
Nested describe blocks?

### ISSUE THREAD

**Issue by AKST** [CapillarySoftware/purescript-mocha#6]
Looks like you can't nest the describe blocks with current api, when you do you get the type error `Duplicate label "describe" in row`.

**Comment by Fresheyeball** [comment]
It's been explicitly disallowed by the purescript compiler, and I don't see a way around it. Way back when I first wrote this nesting `describe` was no problem.

**Comment by paf31** [comment]
`Eff (describe :: Describe | e) a -> Eff (describe :: Describe | e) Unit` should do it.

**Comment by Fresheyeball** [comment]
Sweeeet thanks @paf31

**Comment by Fresheyeball** [comment]
#7

**Comment by Fresheyeball** [comment]
Or, build passed and its been merged. @AKST would you mind checking out this version and ensuring it addresses your use-case? After its been checked I'll update bower.

**Comment by AKST** [comment]
Awesome, sure thing, I'll check it out tonight (Aus time)

**Comment by AKST** [comment]
Sorry I forgot to test this out the other night, but I tried just now and there seems to be a missing module ( `purescript-oo-ffi`), in the bower file it looks like it's a devDependency, as opposed to an average dependency so it wasn't installed by bower.

Other than that it works for me :+1:

**Comment by Fresheyeball** [comment]
oh interesting, my bad.

**Comment by Fresheyeball** [comment]
Ok, its up on bower `v0.0.4`.
